# Generated by Django 5.2.6 on 2025-09-27 22:04

import uuid

import django.core.validators
import django.db.models.deletion
import django_ledger.io.io_core

from django.db import migrations, models


def column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        ]

    return column_name in columns


def table_exists(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return table_name in schema_editor.connection.introspection.table_names(cursor)


def add_field_if_missing(model_name, field):
    def operation(apps, schema_editor):
        Model = apps.get_model("django_ledger", model_name)

        if column_exists(
            schema_editor,
            Model._meta.db_table,
            field.get_attname_column()[1],
        ):
            return

        schema_editor.add_field(Model, field)

    return operation


def create_model_if_missing(model_name):
    def operation(apps, schema_editor):
        Model = apps.get_model("django_ledger", model_name)

        if table_exists(schema_editor, Model._meta.db_table):
            return

        schema_editor.create_model(Model)

    return operation


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_ledger",
            "0025_alter_billmodel_cash_account_and_more",
        ),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_field_if_missing(
                        "StagedTransactionModel",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="django_ledger.customermodel",
                            null=True,
                        ),
                    ),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="stagedtransactionmodel",
                    name="customer_model",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ledger.customermodel",
                        null=True,
                    ),
                ),
            ],
        ),


        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_field_if_missing(
                        "StagedTransactionModel",
                        models.CharField(
                            blank=True,
                            choices=[
                                ("sales", "Sales Receipt"),
                                ("customer_refund", "Sales Refund"),
                                ("expense", "Expense Receipt"),
                                ("expense_refund", "Expense Refund"),
                                ("transfer", "Transfer Receipt"),
                            ],
                            help_text="The receipt type of the transaction.",
                            max_length=20,
                            null=True,
                            verbose_name="Receipt Type",
                        ),
                    ),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="stagedtransactionmodel",
                    name="receipt_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("sales", "Sales Receipt"),
                            ("customer_refund", "Sales Refund"),
                            ("expense", "Expense Receipt"),
                            ("expense_refund", "Expense Refund"),
                            ("transfer", "Transfer Receipt"),
                        ],
                        help_text="The receipt type of the transaction.",
                        max_length=20,
                        null=True,
                        verbose_name="Receipt Type",
                    ),
                ),
            ],
        ),


        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_field_if_missing(
                        "StagedTransactionModel",
                        models.ForeignKey(
                            blank=True,
                            help_text="The Vendor associated with the transaction.",
                            null=True,
                            on_delete=django.db.models.deletion.RESTRICT,
                            to="django_ledger.vendormodel",
                            verbose_name="Associated Vendor Model",
                        ),
                    ),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="stagedtransactionmodel",
                    name="vendor_model",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="The Vendor associated with the transaction.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="django_ledger.vendormodel",
                        verbose_name="Associated Vendor Model",
                    ),
                ),
            ],
        ),


        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_model_if_missing("ReceiptModel"),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ReceiptModel",
                    fields=[
                        (
                            "created",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "updated",
                            models.DateTimeField(auto_now=True, null=True),
                        ),
                        (
                            "markdown_notes",
                            models.TextField(
                                blank=True,
                                null=True,
                                verbose_name="Markdown Notes",
                            ),
                        ),
                        (
                            "uuid",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "receipt_number",
                            models.CharField(
                                max_length=255,
                                verbose_name="Receipt Number",
                            ),
                        ),
                        (
                            "receipt_type",
                            models.CharField(
                                max_length=20,
                                choices=[
                                    ("sales", "Sales Receipt"),
                                    ("customer_refund", "Sales Refund"),
                                    ("expense", "Expense Receipt"),
                                    ("expense_refund", "Expense Refund"),
                                    ("transfer", "Transfer Receipt"),
                                ],
                                verbose_name="Receipt Type",
                            ),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=2,
                                max_digits=20,
                                validators=[
                                    django.core.validators.MinValueValidator(0)
                                ],
                                verbose_name="Receipt Amount",
                            ),
                        ),
                        (
                            "charge_account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="charge_receiptmodel_set",
                                to="django_ledger.accountmodel",
                                verbose_name="Charge Account",
                            ),
                        ),
                        (
                            "customer_model",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="django_ledger.customermodel",
                                verbose_name="Customer Model",
                            ),
                        ),
                        (
                            "ledger_model",
                            models.ForeignKey(
                                editable=False,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="django_ledger.ledgermodel",
                                verbose_name="Ledger Model",
                            ),
                        ),
                        (
                            "receipt_account",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="django_ledger.accountmodel",
                                verbose_name="PnL Account",
                            ),
                        ),
                        (
                            "staged_transaction_model",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                to="django_ledger.stagedtransactionmodel",
                                verbose_name="Staged Transaction Model",
                            ),
                        ),
                        (
                            "unit_model",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="django_ledger.entityunitmodel",
                                verbose_name="Unit Model",
                            ),
                        ),
                        (
                            "vendor_model",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="django_ledger.vendormodel",
                                verbose_name="Vendor Model",
                            ),
                        ),
                    ],
                    options={
                        "abstract": False,
                    },
                    bases=(models.Model, django_ledger.io.io_core.IOMixIn),
                ),
            ],
        ),
    ]